const data = [
  {
    id: 1,
    name: "Classic Icon Bag",
    category: "tote-bags",
    image: "purse1.jpeg",
    price: 30.00,
    rating: 4.5,
    numReviews: 10,
    description: "dummy text",
    quantity: 5,
  },
  {
    id: 2,
    name: "Monica Bag",
    category: "satchels",
    image: "purse2.jpeg",
    price: 20.00,
    rating: 4.2,
    numReviews: 5,
    description: "dummy text",
    quantity: 3,
  },
  {
    id: 3,
    name: "City Moves Bag",
    category: "satchels",
    image: "purse3.jpeg",
    price: 30.00,
    rating: 4.5,
    numReviews: 8,
    description: "dummy text",
    quantity: 2,
  },
  {
    id: 4,
    name: "Beverly Hills Bag",
    category: "satchels",
    image: "purse4.jpeg",
    price: 70.00,
    rating: 4.5,
    numReviews: 8,
    quantity: 10,
  },
  {
    id: 5,
    name: "Miranda Bag",
    category: "cross-bodies",
    image: "purse5.jpeg",
    price: 25.00,
    rating: 4.5,
    numReviews: 8,
    description:
      "The brown crossbody bag is a chic and functional accessory for your everyday needs. Its compact size and adjustable strap make it convenient to carry while adding a touch of elegance to your outfit.",
    quantity: 1,
  },
  {
    id: 6,
    name: "Luxe Edition Bag",
    category: "tote-bags",
    image: "purse6.jpeg",
    price: 70.00,
    rating: 4.5,
    numReviews: 8,
    description: "dummy text",
    quantity: 2,
  },
];

export default data;
